### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by blackxored** [CodementorIO/rest-firebase#10]
Can't tell exactly where but I think there's a memory leak somewhere. I'm not doing anything on the handlers and memory goes up and up and up till it gets oom-killed. 

Memory starts at ~35mb but as soon as it connects it goes up and never stops growing.

Snapshot:
```
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O
22907067cb3b        4.04%               230.7 MB / 536.9 MB   42.97%              122.8 MB / 2.308 MB   0 B / 0 B
```

Besides inside Docker, OSX and Linux display same behavior.

**Comment by godfat** [comment]
Do you have full code to reproduce this?

I do suspect there's memory leak, however I could never track it down. Also, last time I switched to JRuby, memory leak seemed gone. So I also suspect this is a CRuby issue.

**Comment by blackxored** [comment]
I've since figured out that's probably a problem with the size of my collection. There might be a leak given the memory graph, but I wouldn't be able to confirm or further investigate without a clean slate. 

I've tried nodejs and go clients as well, they all seem to hang and get really memory hungry. Obviously the situation is better there (v8, native and what have you) but still a total mess.

Do you have any tips on this subject? I would like to watch (SSE) for every event in a particular collection without loading that particular collection.

**Comment by godfat** [comment]
If that's the case, it's probably not memory leak but memory fragmentation, and it's possible that CRuby's GC didn't work very well against memory fragmentation. (JRuby probably did this much better)

I understand your problem and somehow I feel this is a bad design for Firebase, though I am also not sure if there's a way to make this better. However, I think we could probably work around this with our client, say, we don't serialize the JSON for the first PUT event, skipping the huge data.

Let me see how we could provide this, as an option or something...

**Comment by godfat** [comment]
Do you want to try if this would work well for you? Basically it just skips the first event, which should be the original collection you're referring to.

``` ruby
require 'rest-firebase'

class SkipFirstEvent < RestFirebase::EventSource
  attr_accessor :skipped
  def onmessage *args, &block
    if block || skipped
      super(*args, &block)
    else
      self.skipped = true
    end
  end
end

RestFirebase.event_source_class = SkipFirstEvent
```

**Comment by blackxored** [comment]
First, thanks a lot for taking a look into this. This doesn't work, still won't get into `#onmessage` so it's still loading the huge collection. I'll try adding monkeypatching query to include shallow to test. Will report results :D

**Comment by godfat** [comment]
No problems at all. I guess I don't fully understand your issue then. Why would above still load the huge collection, could you please elaborate?

**Comment by blackxored** [comment]
I've no idea, but I'm starting to believe that it might be a Firebase thing and not this client's problem. Specially given how even Go behaves. Something very weird is going on. Here is my bandwidth graph from yesterday/today:

![Graph](http://d.pr/i/1cdeZ+)

Which is insane. Just for the sake of correctness, my initialization code looks like:

``` ruby
def firebase
  @firebase ||= RestFirebase.new(
    site: ENV['FIREBASE_URL'],
    secret: ENV['FIREBASE_SECRET'],
    auth: ENV['FIREBASE_SECRET']
  )
end

def event_source
  @event_source ||= firebase.event_source('conversations')
end

# ...
```

I wanna hear your thoughts, but probably the memory issues I'm seeing it's that it's indeed loading the collection entirely, so as I haven't let it finish (or the OS does in the case of docker since it gets killed), it hadn't have a chance to clean itself since it's not done.

In case it helps, I get a "Connected to firebase" message that I put on `#onopen`, and then hangs there never reaching my `#onmessage`, i.e. not getting any events that I can process. Given your last example it does reach the class's `#onmessage` but then it goes to query and takes forever. Hopefully it was clear enough.

**Comment by godfat** [comment]
Umm... then I guess your data is really huge (more than 4G!?), that even skipping parsing the JSON to Ruby objects, building the whole string already took too much memory.

If that's the case, then it's much harder to skip that. Even if we could skip it, we're just throwing data sent from Firebase away, still wasting bandwidth, and we have no way around that because that's just how Firebase works.

I think they should provide an option to turn this behaviour off. Just checked the document, I was not aware we could pass `shallow=true` to... somehow limit the data. But if they're still returning all the keys, then it still won't work well with huge data (e.g. millions of keys).

Perhaps we should ask them to implement something like `observe=true` so that it won't return the dataset, but just fire modification events.

**Comment by blackxored** [comment]
That's kind of the thing, my data is only 900MB :scream:.

About `shallow` I'd do my research since apparently you can't pass other query params with, probably besides `auth` and in my limited experience it's unreliable. In my testing sometimes didn't even work, I don't know. Found out about it looking at the source of the firego client. 

I'll take things to Firebase, keep an eye out for memory, but I think this issue is more of their/my issue than this client's, sorry :D.

**Comment by godfat** [comment]
I guess given how Firebase works currently, you're going to have a hard time if your data is more than 100M :o Ruby objects might take 3 times more memory, therefore 100M could result in 300M memory for Ruby, and even if it took zero memory, you won't want to download 900M each time you restart the server/daemon or just when we're reconnecting to Firebase due to disconnection!

I also tried to use `limitToFirst` and `limitToLast`, but it didn't work well. I guess they're not playing well with event stream.

No problems at all. I believe we're also suffering from this, but just that we don't have so much data right now, so it's not too obvious, but I believe everyone using Firebase as storage (or even notification channel) would face this eventually.

Let me know if there's anything else I could help, and thanks for trying this client.

**Comment by blackxored** [comment]
I'm trying to get their support involved. Will keep you posted if you want.

**Comment by godfat** [comment]
Yes please, thank you.

**Comment by godfat** [comment]
@blackxored Hi, any updates you could share? :)

**Comment by blackxored** [comment]
Sadly I had to re-architect the data. It seems that it's a limitation
they're not that willing to fix.

On Tue, Mar 8, 2016 at 8:15 AM Lin Jen-Shin (godfat) <
notifications@github.com> wrote:

> @blackxored <https://github.com/blackxored> Hi, any updates you could
> share? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CodementorIO/rest-firebase/issues/10#issuecomment-193638235>
> .
>
-- 
Best Regards,

Adrian Perez
http://adrianperez.org | @blackxored

**Comment by godfat** [comment]
Ok, got it, thanks. I guess then I could conclude that Firebase is only good for communication channel, but not really for storage. We should still use a real database after all.

**Comment by godfat** [comment]
Since this is not memory leak and we can't do anything to it, close for now. They really have bad support for REST API.
